# Generated by Django 3.2.1 on 2021-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='CVV',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pay',
            name='Creditcardnumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ExpYear',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pay',
            name='Zip',
            field=models.BigIntegerField(),
        ),
    ]
