# Generated by Django 3.2.1 on 2021-05-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210517_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payme',
        ),
    ]
