# Generated by Django 3.2.1 on 2021-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_payme_payment1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.BigIntegerField()),
                ('cardname', models.CharField(max_length=50)),
                ('cardnumber', models.BigIntegerField()),
                ('expmonth', models.CharField(max_length=50)),
                ('expyear', models.BigIntegerField()),
                ('cvv', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='payment1',
        ),
    ]
