# Generated by Django 3.2.1 on 2021-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210517_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('femail', models.EmailField(max_length=50)),
                ('fphone', models.BigIntegerField()),
                ('fskills', models.CharField(max_length=100)),
                ('fStreet', models.CharField(max_length=50)),
                ('fCity', models.CharField(max_length=50)),
                ('fState', models.CharField(max_length=50)),
                ('fCode', models.BigIntegerField()),
            ],
        ),
    ]
